### ISSUE TITLE
Devtools not showing up in developer toolbar

### ISSUE THREAD

**Issue by SachaG** [apollostack/apollo-client-devtools#8]
I haven't been able to get the Apollo Devtools to show up reliably in my developer toolbar.

According to @stubailo:

> I think it's because we only check for Apollo existence once here: https://github.com/apollostack/apollo-client-devtools/blob/bc84febe32d7d50d4d547678890cdfeec2cc2610/extension/devtools.js#L1

**Comment by stubailo** [comment]
Yeah, probably a good idea to set that up to poll on an interval.

**Comment by Darkbladecr** [comment]
I have been struggling to get the tools to appear on my development panel as well. I am currently running an angular 1.6 project. I am initializing apollo as below, with the `connectToDevTools` argument as well. `window.__APOLLO_CLIENT__` does not seem to be available, but I am not sure what I should do to enable it within the window?

```
import ApolloClient from 'apollo-client';

function config(apolloProvider) {
	const client = new ApolloClient({ connectToDevTools: true });
	apolloProvider.defaultClient(client);
}
```

**Comment by stubailo** [comment]
what version are you on? basically here is the code for that: https://github.com/apollostack/apollo-client/blob/42b5a4cb1cf2728d803b1aca9bbfa58ca4c36c64/src/ApolloClient.ts#L239-L251

It looks correct to me, but maybe something is buggy, would appreciate a review

**Comment by Darkbladecr** [comment]
I appear to be on an old version, let me update and report back.

**Comment by Philip-Nunoo** [comment]
@Darkbladecr can you confirm this issue is resolved. Having similar problems here

**Comment by Darkbladecr** [comment]
Yes after upgrading everything works.

**Comment by stubailo** [comment]
Closing this specific issue, please open a new one with more detailed information if you are still experiencing problems.

**Comment by RafaelCosman** [comment]
@stubailo I'm still experiencing problems with the dev tools not showing up.

**Comment by pcooney10** [comment]
+1

**Comment by arjunagl** [comment]
+1

**Comment by jimmybrawn** [comment]
+100^100

**Comment by kimobrian** [comment]
I had an issue where it kept telling me enable dev tools by setting `connectToDevTools` to true when I had already done it. I simply disabled the extension, hard-reloaded my app and enabled the extension then reloaded the app again and it showed up.

**Comment by MichelDiz** [comment]
I have this issue, but when I use in "incognito window" (anonymous window of the chrome) works fine. What it would be?
